name: mac

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15
          - macos-15-intel
          - macos-26
          - macos-26-intel
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install poco yaml-cpp

      - name: Configure
        run: cmake -B build -DCMAKE_INSTALL_PREFIX=$HOME/omni-install

      - name: Build
        run: cmake --build build

      - name: Install
        run: cmake --install build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
